DROP TABLE IF EXISTS plots;
DROP TABLE IF EXISTS audience;
DROP TABLE IF EXISTS person;
DROP TABLE IF EXISTS team;
DROP TABLE IF EXISTS job;
CREATE TABLE audience (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  audience TEXT UNIQUE NOT NULL
);
CREATE TABLE team (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  team TEXT NOT NULL
);
CREATE TABLE job (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  job TEXT NOT NULL
);
CREATE TABLE plots (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  plotName TEXT UNIQUE NOT NULL,
  imagePath TEXT NOT NULL,
  plotData TEXT NOT NULL,
  audience INTEGER REFERENCES audience(id)
);
CREATE TABLE person (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  firstName TEXT NOT NULL,
  lastName TEXT NOT NULL,
  email TEXT NOT NULL,
  audience INTEGER REFERENCES audience(id),
  job INTEGER REFERENCES job(id),
  team INTEGER REFERENCES team(id)
);